# Generated by Django 2.0.2 on 2018-04-04 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UploadItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='item_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expired',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 21, 1, 56, 820896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expired',
            name='item_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
